//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSoftFaceApp.EntityFrameDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_attend
    {
        public long attend_id { get; set; }
        public Nullable<int> rule_id { get; set; }
        public Nullable<long> course_id { get; set; }
        public Nullable<int> classroom_id { get; set; }
        public string describes { get; set; }
        public string attend_status { get; set; }
    }
}
