//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSoftFaceApp.EntityFrameDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_attendrule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_attendrule()
        {
            this.t_attend = new HashSet<t_attend>();
        }
    
        public int rule_id { get; set; }
        public string rule_name { get; set; }
        public Nullable<System.DateTime> course_start_time { get; set; }
        public Nullable<System.DateTime> course_end_time { get; set; }
        public Nullable<System.DateTime> check_start_time { get; set; }
        public Nullable<System.DateTime> check_end_time { get; set; }
        public string nomal_late_min { get; set; }
        public string nomal_leave_early_min { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_attend> t_attend { get; set; }
    }
}
