//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSoftFaceApp.EntityFrameDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_attenditem
    {
        public long attendItem_id { get; set; }
        public long attend_id { get; set; }
        public string student_id { get; set; }
        public Nullable<System.DateTime> attend_time { get; set; }
        public string attend_reslut { get; set; }
    
        public virtual t_attend t_attend { get; set; }
        public virtual t_student t_student { get; set; }
    }
}
