//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSoftFaceApp.EntityFrameDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_attend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_attend()
        {
            this.t_attenditem = new HashSet<t_attenditem>();
        }
    
        public long attend_id { get; set; }
        public Nullable<int> rule_id { get; set; }
        public Nullable<long> course_id { get; set; }
        public string classroom_id { get; set; }
        public string describes { get; set; }
        public string attend_status { get; set; }
        public string attend_name { get; set; }
        public string manager { get; set; }
        public Nullable<System.DateTime> attend_create_time { get; set; }
        public Nullable<int> class_id { get; set; }
    
        public virtual t_attendrule t_attendrule { get; set; }
        public virtual t_classroom t_classroom { get; set; }
        public virtual t_course t_course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_attenditem> t_attenditem { get; set; }
    }
}
