//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSoftFaceApp.EntityFrameDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_camera
    {
        public int camera_id { get; set; }
        public string camera_code { get; set; }
        public Nullable<int> classroom_id { get; set; }
        public string camera_ip { get; set; }
        public Nullable<int> camera_port { get; set; }
        public string camera_user { get; set; }
        public string camera_pwd { get; set; }
    
        public virtual t_classroom t_classroom { get; set; }
    }
}
