//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSoftFaceApp.EntityFrameDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_faceinfo
    {
        public long id { get; set; }
        public string studnet_id { get; set; }
        public string face_id { get; set; }
        public Nullable<long> group_id { get; set; }
        public byte[] face_feature { get; set; }
        public string image_path { get; set; }
    
        public virtual t_student t_student { get; set; }
    }
}
