//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSoftFaceApp.EntityFrameDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_log
    {
        public long ID { get; set; }
        public string USERNAME { get; set; }
        public string OPERATION { get; set; }
        public Nullable<decimal> TIME { get; set; }
        public string METHOD { get; set; }
        public string PARAMS { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string location { get; set; }
    }
}
