//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARCSoftFaceApp.EntityFrameDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_student()
        {
            this.t_attenditem = new HashSet<t_attenditem>();
            this.t_face = new HashSet<t_face>();
        }
    
        public string student_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public string student_name { get; set; }
        public string student_gender { get; set; }
        public string student_email { get; set; }
        public string student_qq { get; set; }
        public Nullable<long> user_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_attenditem> t_attenditem { get; set; }
        public virtual t_classes t_classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_face> t_face { get; set; }
        public virtual t_user t_user { get; set; }
    }
}
